##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This role calls nested_main.yaml for each member/peer
---
- name: Create Cactus connector
  include_tasks: nested_main.yaml
  vars:
    name: "{{ member.name | lower }}"
  loop: "{{ members }}"
  loop_control:
    loop_var: member
  when: 
  - member.cactus_connector is defined
  - member.cactus_connector == "enabled"
