apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: warehouse-vaultk8s-job
  namespace: warehouse-bes
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: warehouse-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/vault-k8s-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    metadata:
      name: warehouse-vaultk8s-job
      namespace: warehouse-bes
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        pullPolicy: IfNotPresent

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://10.0.0.112:8200
      authpath: besuwarehouse
      policy: vault-crypto-warehouse-bes-warehouse-ro
      policydata: "{\n  \"policy\": \"path \\\"secretsv2/data/warehouse-bes/crypto/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\", \\\"create\\\", \\\"update\\\"]\n  }\n  path \\\"secretsv2/data/warehouse-bes/smartContracts/*\\\" {\n    capabilities = [\\\"read\\\", \\\"list\\\"]\n  }\"\n}"
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred

    k8s:
      kubernetes_url: https://10.0.0.112:6443
