##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build corda os docker images triggered by :
#  - push on develop branch for latest tags
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Corda Opensource docker images

on:
  workflow_dispatch:
    inputs:
      corda_version:
        description: 'Enter Corda OS Version to build'
        required: true
        default: '4.9'
        type: choice
        options:
        - '4.4'
        - '4.7'
        - '4.9'
  create:
    tags:
      - v*
  push:
    branches:
      - develop
    paths:
      - 'platforms/r3-corda/images/**'
      - '.github/workflows/img_platform_corda.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to develop branch, create docker tags latest
  cordaOS-latest:
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase IMAGE_PATH
      id: image_path_format
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ env.IMAGE_PATH }}

    - name: Build and push cordaOS node latest
      if: github.event.inputs.corda_version == ''
      id: corda_node_latest
      uses: docker/build-push-action@v2
      with:
        file: platforms/r3-corda/images/Dockerfile-corda-tls
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-corda:latest

    - name: Build and push cordaOS node with provided version
      if: github.event.inputs.corda_version != ''
      id: corda_node_version
      uses: docker/build-push-action@v2
      with:
        file: platforms/r3-corda/images/Dockerfile-corda-tls
        push: true
        build-args: |
          BUILDTIME_CORDA_VERSION=${{ github.event.inputs.corda_version }}
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-corda:latest,${{ steps.image_path_format.outputs.lowercase }}/bevel-corda:${{ github.event.inputs.corda_version }}

  cordaOS-release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase IMAGE_PATH
      id: image_path_format
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ env.IMAGE_PATH }}

    - name: Build and push cordaOS node release and stable tag ${{ steps.vars.outputs.tag }}
      id: corda_node_release
      uses: docker/build-push-action@v2
      with:
        file: platforms/r3-corda/images/Dockerfile-corda-tls
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-corda:${{ steps.vars.outputs.tag }},${{ steps.image_path_format.outputs.lowercase }}/bevel-corda:stable
